---
title: "Seattle College Enrollments"
author: "Brian Holt"
date: "1/26/2020"
output:
  html_document:
    df_print: paged
  rmdformats::html_clean:
    TOC: yes
    highlight: kate
---

```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## Packages

```{r, packages and data,echo=T}
load('main.df')
library(tidyverse)
library(lubridate)
library(purrr)
```


The following drops Summers

```{r quick processing and graphing of enrollments,include =T}
main.df %>% select(college,code, Season,yr,scrap_enrol,site_clus_enrol) %>% 
  mutate(Date=
           ifelse(grepl("A|B|9903|9904",code),
                  paste0('20',yr),
                  paste0('19',yr))) %>% 
  mutate(Date=case_when(
    Season=='Summer'~paste0(Date,'-','07','-','20'),
    Season=='Fall'~paste0(Date,'-','10','-','20'),
    Season=='Winter'~paste0(Date,'-','01','-','20'),
    Season=='Spring'~paste0(Date,'-','04','-','20')
  )) %>% 
  mutate(Date = ymd(Date)) %>% filter(Season!="Summer") %>% 
  
  ggplot(aes(x=Date,y=scrap_enrol,color=Season))+geom_line()+#geom_smooth(method="loess")+
  #geom_vline(xintercept = as.numeric(ymd('2009-10-20')))+
  facet_wrap(~college)
  #geom_hline(yintercept = 10568)
```

This table looks at the highest enrollment (around 2009) and compares the relative drop amoung the colleges.
```{r, drop from high, echo=F }
main.df %>% select(college,code, Season,yr,scrap_enrol,site_clus_enrol) %>% 
  mutate(Date=
           ifelse(grepl("A|B|9903|9904",code),
                  paste0('20',yr),
                  paste0('19',yr))) %>% 
  mutate(Date=case_when(
    Season=='Summer'~paste0(Date,'-','07','-','20'),
    Season=='Fall'~paste0(Date,'-','10','-','20'),
    Season=='Winter'~paste0(Date,'-','01','-','20'),
    Season=='Spring'~paste0(Date,'-','04','-','20')
    )) %>% 
  mutate(Date = ymd(Date)) %>% filter(Season!="Summer") %>% group_by(college) %>% 
  summarise(max=max(scrap_enrol+site_clus_enrol),
            recent_qrt= sum(scrap_enrol[code=='B902']+
                              site_clus_enrol[code=='B902']),
            Percent_drop=( round((max-recent_qrt)/max*100,1)))
  
  
```



```{r stitching it together, include =T}
datalist <- list()
for (i in 1:nrow(main.df)){
  row.count <- nrow(main.df$scrap_tbl[[i]])
  datalist[[i]] <- main.df$scrap_tbl[[i]]
  datalist[[i]] <- (cbind(main.df[i,2:5],datalist[[i]]))
  }
df <- do.call(rbind,datalist)

```

Change college from numbers

```{r change from factor to character to change back, include =T}

df<- df %>% mutate(college=as.character(college)) %>% 
  mutate(college = as.factor(ifelse(college=='062',"Central",ifelse(college=='063',"North","South"))))

```



```{r calc enrolled by college over time, include=T}
df %>% select(college,code,Season,yr,Enrolled) %>% 
  mutate(Date=
           ifelse(grepl("A|B|9903|9904",code),
                  paste0('20',yr),
                  paste0('19',yr))) %>% 
  mutate(Date=case_when(
    Season=='Summer'~paste0(Date,'-','07','-','20'),
    Season=='Fall'~paste0(Date,'-','10','-','20'),
    Season=='Winter'~paste0(Date,'-','01','-','20'),
    Season=='Spring'~paste0(Date,'-','04','-','20')
    )) %>% 
  mutate(Date = ymd(Date)) %>% filter(Season!="Summer") %>% 
  group_by(college,Date,Season) %>% summarise(sum=sum(Enrolled)) %>% 
  ggplot(aes(x=Date,y=sum,color=Season))+geom_line()+facet_wrap(~college)

```
  
```{r, prove that differences bw enrollof scrap vs site, comments=T}
  
##at some point would be worth confirming that the scrapped data looks like the calc'd data

```  
  
  
  #summer 04 the 'new' AU codes went into effect
  
  
  
```{r calc enrolled vs State FTE by Season codes over time, include=T}
df %>% select(college,code,Season,yr,Enrolled,State.FTES) %>% 
  mutate(Date=
           ifelse(grepl("A|B|9903|9904",code),
                  paste0('20',yr),
                  paste0('19',yr))) %>% 
  mutate(Date=case_when(
    Season=='Summer'~paste0(Date,'-','07','-','20'),
    Season=='Fall'~paste0(Date,'-','10','-','20'),
    Season=='Winter'~paste0(Date,'-','01','-','20'),
    Season=='Spring'~paste0(Date,'-','04','-','20')
    )) %>% 
  mutate(Date = ymd(Date)) %>% filter(Season!="Summer") %>% 
  group_by(college,Date,Season) %>% summarise(Enrollment_Total=sum(Enrolled),State_FTE_tot=sum(State.FTES)) %>% 
  ggplot(aes(x=Date,y=Enrollment_Total,color=Season))+geom_line()+geom_line(aes(x=Date,y=State_FTE_tot))+facet_wrap(~college)+title("Total Enrollment stacked above Total State FTE's")
#+theme(legend.position = "none")

```